### PR TITLE
Make file globbing in DNX case insensitive

### PR DESCRIPTION
**Pull request by troydai**
Address: https://github.com/aspnet/dnx/issues/1645

### CODE REVIEW

**Comment by troydai** [comment]
Tested in Universe and on Linux as well.

**Comment by troydai** [comment]
Ping @davidfowl 
Nothing to review here, i'll merge this shortly.

**Comment by troydai** [comment]
/cc @muratg @anurse @victorhurdugaci @BrennanConroy 

This makes our globbing case insensitive.

**Comment by BrennanConroy** [comment]
fix hash

**Pull request merged**
