### PR TITLE
Fix dnx trace message

### PR DESCRIPTION
**Pull request by ellismg**
My previous changes caused garbage to be printed to the console when DNX_TRACE=1 was set on Windows.  This change fixes that.

I also updated the TPA list since when I built new stuff was pended.

### CODE REVIEW

**Comment by ellismg** [comment]
@davidfowl PTAL, this addresses the issue you told me about.

**Comment by davidfowl** [comment]
@anurse Can you make sure you didn't introduce this new dependency into the TPA list: - System.Diagnostics.Tracing

**Comment by davidfowl** [comment]
:shipit:

**Comment by ellismg** [comment]
Per conversation with @davidfowl, I will just merge the actual dnx change and hold of on the TPA updates

**Comment by anurse** [comment]
System.Diagnostics.Tracing is ETW stuff, I don't see any reference to it in Logging, so I'm not sure how it would have arrived from that. I'll do some spelunking.

**Comment by anurse** [comment]
@davidfowl I don't see System.Diagnostics.Tracing anywhere, not sure how it would end up in the TPA in this PR. It's not appearing in the TPA in my local dev build.

**Pull request closed without merging**
