### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@hishamco__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by Eilon** [comment]
Nice catch!

@victorhurdugaci can you merge?

**Comment by victorhurdugaci** [comment]
Done. Thanks for the contribution, @hishamco!

**Comment by hishamco** [comment]
You are welcome @victorhurdugaci

**Pull request merged**
