### PR TITLE
Ensure current directory is set to the project directory #3196

### PR DESCRIPTION
**Pull request by schotime**
Related to issue #3196.
Sets the current directory to the project directory.

### CODE REVIEW

**Comment by davidfowl** [comment]
Setting the working directory is always a bad idea. If you really need that, do it in your application.

**Comment by schotime** [comment]
So how is #3196 fixed then? Surely is should work the same way whether I run it from the directory where project.json is vs a parent directory specifying the project directory (-p).

**Comment by davidfowl** [comment]
The application base is set to the project directory when using `-p`. The config API uses the application base directory to find relative config files.

**Comment by davidfowl** [comment]
Try using AddJsonFile instead of using the provider directly https://github.com/aspnet/Configuration/blob/dev/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationExtensions.cs#L60

**Comment by schotime** [comment]
Victory!!!

**Pull request closed without merging**
