### PR TITLE
Remove System.Data.SqlClient from Microsoft.Dnx

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @BrennanConroy \ @anurse \ @divega

**Comment by anurse** [comment]
:shipit: (assuming this actually fixes the EF issue)

**Comment by divega** [comment]
@anurse @pranavkm we know removing the sni.dll from the runtime folder fixes the issue but we don't know exactly why. 

Can you easily tell from the code which package exactly would we currently extract sni.dll from? Several packages contain it and I would like to double-check before I report it back to the SqlClient folks.

**Comment by divega** [comment]
Other than that :shipit:

**Comment by davidfowl** [comment]
Probably because we're getting it from the packages folder

**Pull request merged**
