### PR TITLE
Get rid of IFileWatcher

### PR DESCRIPTION
**Pull request by davidfowl**
Part of #2683

/cc @anurse @victorhurdugaci

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Will this break tooling?

**Comment by moozzyk** [comment]
does this break dnx-watch?

**Comment by davidfowl** [comment]
@victorhurdugaci No, in beta8, @BillHiebert removed the --watch flag AFAIK

@moozzyk No, the watcher has the logic to watch the files :smile:

**Comment by moozzyk** [comment]
:ship::it: (once travis passes)

**Pull request closed without merging**
