### PR TITLE
Add new CoreCLR dependency

### PR DESCRIPTION
**Pull request by BrennanConroy**
@davidfowl @troydai

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:

**Comment by BrennanConroy** [comment]
They just emailed me, and the binary has been renamed. They also suggested taking any System.*.so/dylib for the upcoming beta. Thoughts?

**Comment by davidfowl** [comment]
Sure, if that's the suggestion then modify the exclude logic a bit.

**Comment by BrennanConroy** [comment]
@davidfowl

**Comment by BrennanConroy** [comment]
7fd246c0b5e9c134786f3eeac7ff6774cdc498a2

**Pull request closed without merging**
