### PR TITLE
Fix IRuntimeEnvironment exception

### PR DESCRIPTION
**Pull request by victorhurdugaci**
Fixes https://github.com/aspnet/dnx/issues/1665

cc @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
The try catch is fine but why doesn't it work on win7?

**Comment by victorhurdugaci** [comment]
Because I was catching the wrong exception. On Win7 the api set DLL is there but it is missing that API. So it was throwing an entry point not found instead of DLL not found

**Comment by davidfowl** [comment]
Can we also change this code to be lazy? It would be great if we could avoid all first chance exceptions on the startup path.

**Comment by GuardRex** [comment]
Queued at AppVeyor for over an hour. Is that normal?

... and after the AppVeyor build, will `dnvm update-self` get me back to work?

**Comment by victorhurdugaci** [comment]
@GuardRex yes, it can take a while. Now it is done
@davidfowl sure, let me update the code

**Comment by victorhurdugaci** [comment]
@GuardRex no, AppVeyor does not produce any bits. You will have to wait for this PR to be merged and then run "dnvm upgrade". Or, you can get my code and build dnx locally

**Comment by GuardRex** [comment]
ok, thanks

**Comment by GuardRex** [comment]
@victorhurdugaci My attempts to `dnvm install 1.0.0-beta5-11561 -r coreclr -arch x64` (and `-11560`) failed to get me a `dnu restore` that works. What's the ETA on a merge like this (I see a bunch of PR's have been around for days)? If it's going to be a while, then I will need to build locally ... or do you know what I'm doing wrong in trying to get an older, working runtime installed?

**Comment by victorhurdugaci** [comment]
I'll merge this tomorrow after I update the PR. 

Meanwhile, try an even older build like 11540 or even 11530 because we produce more than one build per day. I can't check right now which is last build before my previous change.

**Comment by GuardRex** [comment]
ah ... that explains it then ... I simply didn't go back far enough. Thanks.

**Pull request merged**
