### PR TITLE
Add coreapp support to dnx

### PR DESCRIPTION
**Pull request by pakrym**
https://github.com/aspnet/dnx/issues/3378

@anurse

### CODE REVIEW

**Comment by davidfowl** [comment]
limp along dnx :smile: :shipit:

**Comment by anurse** [comment]
:shipit:

**Comment by ghost** [comment]
:+1: 
BTW, there is [103 commits difference](https://github.com/aspnet/dnx/compare/1.0.0-rc1-update2...dev) between `rc1-update2` tag and `dev` branch (and it's counting).
Is there a plan to include those in next version of dnx, if everything is working as expected in `dev` branch?

**Comment by analogrelay** [comment]
There will be no next version of DNX. The only reason we are updating it was to allow our current builds which still used it to work. DNX is being replaced with the .NET Core CLI

**Comment by ghost** [comment]
Thanks @anurse! I am waiting for CLI release. Hope we the upgrade process from dnx->cli for existing projects will be seamless.. as I have written down the custom deployment scripts for Kudu auto-deploy.

**Pull request closed without merging**
