### PR TITLE
Rename Microsoft.Dnx.Compilation.Abstractions to Microsoft.Extensions.Compilation.Abstractions

### PR DESCRIPTION
**Pull request by pakrym**
@davidfowl  @pranavkm

### CODE REVIEW

**Comment by pranavkm** [comment]
Any idea why Travis is failing? Changes look :shipit:

**Comment by pakrym** [comment]
@pranavkm, Looks like a dependency on other library that uses Dnx.Compilation, so we get two versions of classes

**Comment by pranavkm** [comment]
Isn't that a problem? Who's still trying to pull in `Microsoft.Dnx.Compilation.Abstractions`?

**Comment by pakrym** [comment]
It looks like test host, we'll need disable test to pull dnx build through

**Comment by pranavkm** [comment]
:shipit:

**Pull request merged**
