### PR TITLE
Fix package restore timeout on Mono

### PR DESCRIPTION
**Pull request by mconnew**
On mono, concurrent package download is 1, but up to 50 are attempted
at a time. This causes the requests to queue up and HttpClient times
out after 100 seconds. This change adds a semaphore to only allow
ServicePointManager.DefaultConnectionLimit number of requests to
be using HttpClient at a time.

Addresses #3149

### CODE REVIEW

**Comment by mconnew** [comment]
Is there a way to re-run the ci build? It looks like the build stalled downloading packages required to even build my code change on OSX. It hadn't even got to compiling the code. The CI build ran fine on Linux.

**Comment by davidfowl** [comment]
We aren't really changing DNX anymore (it's being retied in favor of the .NET CLI). Can you use the CoreCLR version instead?

**Comment by mconnew** [comment]
I think I might be missing something but it looks like this is the code that .NET CLI uses. When using .NET CLI tool to restore packages, it [executes](https://github.com/dotnet/cli/blob/master/src/dotnet-restore/Dnx.cs) a script ([dotnet-dnx.cmd](https://github.com/dotnet/cli/blob/master/scripts/dotnet-dnx.cmd)) which simply does the following:
```
"%~dp0dnx\dnx" "%~dp0dnx\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" %*
```
There's a [bash script](https://github.com/dotnet/cli/blob/master/scripts/dotnet-dnx.sh) too which does the equivalent on unix. This uses the implementation in Microsoft.Dnx.Tooling.dll which has a bug on Mono, and is fixed by the PR I submitted. Unless I've missed something, isn't this still the active code base being used by .NET CLI?

**Comment by BrennanConroy** [comment]
It wont be used by the CLI very soon

**Comment by davidfowl** [comment]
@mconnew It's also only CoreCLR, it doesn't use mono.

**Comment by davidfowl** [comment]
Ping @mconnew. Can you use either the CoreCLR DNX or the .NET CLI?

**Comment by mconnew** [comment]
We don't have direct control over our build tools, we use the same infrastructure is the dotnet/corefx repo. At the moment we're using a mono based version of dnx. There are plans in place to move to running dnx restore on coreclr (presumably .NET CLI), but it's not ready yet. This bug means at the moment we can't do our own CI tests building on Linux directly but instead need to cross compile on windows and copy our build to unix with a convoluted test script. Otherwise we sometimes need to rerun our build repeatedly until we have everything downloaded before we even compile. I've seen it take up to 5 times.

**Comment by davidfowl** [comment]
@weshaggard @ericstj Can the build tools use the CoreCLR version of DNX or at least allow overriding it? I don't want to do anymore code changes to our restore because it's going away and will get lost when we switch over to nuget anyways (which is happening this week).

**Comment by weshaggard** [comment]
We just make a change recently to switch to dotnet restore for BuildTools so this should already be handled.

**Comment by davidfowl** [comment]
@mconnew Seems like that should resolve the problem. I'm closing this out.

**Comment by Cream2015** [comment]
sir，could you please help me to fixed a problem which dnx restore in ubuntu development,now the problem not solute three days .......http request timed out....

**Pull request closed without merging**
