### PR TITLE
Add functional test for DesignTimeHostCompiler

### PR DESCRIPTION
**Pull request by troydai**
#3012 

/cc @davidfowl @moozzyk @muratg @victorhurdugaci

### CODE REVIEW

**Comment by muratg** [comment]
:shipit:

**Comment by troydai** [comment]
Seems to be failing on Travis. Investigating.

**Comment by troydai** [comment]
It's a failure only repos on Mono. Investigating...

**Comment by troydai** [comment]
Updated. Compiler doesn't generate `pdb` on Mono. Updated tests accordingly.

**Comment by muratg** [comment]
:+1:

**Pull request merged**
