### PR TITLE
Use DrainTillFirst to speed up tests

### PR DESCRIPTION
**Pull request by troydai**
To shorten test time

/review @davidfowl @JunTaoLuo 
/cc @muratg @victorhurdugaci @BrennanConroy

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Looks good to me

**Comment by victorhurdugaci** [comment]
Till -> Until

**Comment by victorhurdugaci** [comment]
Or SkipWhile

**Comment by victorhurdugaci** [comment]
Or SkipUntil

**Comment by victorhurdugaci** [comment]
Looks good otherwise

**Comment by troydai** [comment]
I will not change the name of the `DrainTillFirst` for now. It's not in the scope of this change. But I will consider renaming. Besides that it looks cool. Some one sign off?

**Comment by JunTaoLuo** [comment]
Open a new issue to track the renaming? It's a minor issue so other than that :shipit:

**Pull request merged**
