### PR TITLE
Removing dnu sources

### LINKED ISSUE #2455: `dnu pack` hangs at "Embedding repository information..."
Seeing this issue quite regularly. `dnu pack` completes and the build script hangs for 3-5 minutes at `Embedding repository information...`. Terminating the spawned git.exe sorts this issue out. 

Process Explorer snapshot for reference:
screenshot
Reproed this with dnx-clr-win-x86.1.0.0-beta7-12335

That said, embedding the commit information for a work in progress commit seems quite pointless. Why isn't this an opt-in feature so the CI sets it up for you?

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #2455

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @victorhurdugaci

**Comment by muratg** [comment]
Looks good, :shipit: from me, but please wait for @victorhurdugaci's response as well.

Also, I think it would make sense to keep the feature code in some form as we intend to bring it back at some point post-V1.

**Comment by victorhurdugaci** [comment]
Meh, not impressed that we are removing this but the change itself looks good.

Btw, you have to update the `project.json` files in every repo to remove the `repository` information

**Comment by victorhurdugaci** [comment]
:shipit:

**Comment by victorhurdugaci** [comment]
@muratg the code will be in git :)

**Comment by davidfowl** [comment]
@pranavkm @victorhurdugaci @muratg We should write an announcement

**Comment by muratg** [comment]
@victorhurdugaci So another run of touching all the repos. Would this be required to be checked in as soon as this goes in or can it wait? It would tell @pranavkm when to actually merge this.

@davidfowl agreed. @pranavkm or @victorhurdugaci should volunteer :)

**Comment by davidfowl** [comment]
I think leaving in the repo information is fine actually. It's harmless.

**Comment by muratg** [comment]
:+1:

**Comment by pranavkm** [comment]
Yeah, we could use it once this feature gets eventually revived. No point in causing random diffs.

**Comment by pranavkm** [comment]
@muratg hopefully all it would take is reverting this changeset to revive this feature in the future.

**Comment by pranavkm** [comment]
Do we need a discussion thread for the announcement or is it more of an FYI?

**Comment by davidfowl** [comment]
@pranavkm keep the discussion thread in case people want to complain

**Comment by NeelBhatt** [comment]
:+1:  for this! And I guess this should be announced!

**Comment by pranavkm** [comment]
Announcement thread: https://github.com/aspnet/Announcements/issues/66
DNX tracking thread: https://github.com/aspnet/dnx/issues/2699

**Pull request closed without merging**
