### PR TITLE
Move CommandLineUtils to Common

### PR DESCRIPTION
**Pull request by BrennanConroy**
#3246

### CODE REVIEW

**Comment by muratg** [comment]
I think it's OK to close this one.  Do we have some other repo using the one from Common now (even if it's just a test)?

**Comment by davidfowl** [comment]
Close? Why not just do this?

**Comment by muratg** [comment]
Do we care about dnx?  We plan to stop even building it hopefully soon, don't we?

**Comment by davidfowl** [comment]
No but this moves the library out of DNX. Are you suggesting we just leave it in and have a copy in Common? That's fine I guess.

**Comment by muratg** [comment]
Yeah, [the one in Common](https://github.com/aspnet/Common/pull/69) is being reviewed. I think we can close this one in the DNX repo.

**Pull request closed without merging**
