### PR TITLE
Anurse/fix release

### PR DESCRIPTION
**Pull request by anurse**
/cc @troydai

### CODE REVIEW

**Comment by troydai** [comment]
@anurse do we still need this PR?

**Comment by anurse** [comment]
Guh, I don't even remember what it was for... @davidfowl ?

**Comment by anurse** [comment]
I just remembered why we need it :). I'll rebase it and use it to implement the compatibility matrix stuff we need to do as well.

**Comment by anurse** [comment]
Actually, we already have it in release. I'm just so turned around by all this :)

**Pull request closed without merging**
