### PR TITLE
Fix DnuCommands_Install_InstallsWorkingCommand test failure

### PR DESCRIPTION
**Pull request by pakrym**
@JunTaoLuo @anurse @BrennanConroy

### CODE REVIEW

**Comment by BrennanConroy** [comment]
:+1: is that the only affected test?

**Comment by pakrym** [comment]
yes

**Comment by davidfowl** [comment]
:shipit:

**Comment by BrennanConroy** [comment]
I think you need to add the runtime to the front of the path instead of replacing the path

**Pull request merged**
