### PR TITLE
Making dnx.clr.managed strong named... again

### PR DESCRIPTION
**Pull request by moozzyk**
The appdomain manager has to have a real strong name (as opposed to fake one) otherwise bootstrapping CLR will fail due to strong name verification.

### CODE REVIEW

**Comment by moozzyk** [comment]
:watch:

**Comment by davidfowl** [comment]
@jkotas Is there a way around this?

**Comment by jkotas** [comment]
I doubt that there is a way around it.

**Comment by moozzyk** [comment]
@davidfowl meaning it is good to go right? (It's blocking #2024)

**Pull request merged**
