### PR TITLE
Update the makefile.shade for file header

### PR DESCRIPTION
**Pull request by troydai**
To auto-generate tpa.cpp with correct file headers

@Eilon @NTaylorMullen

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
:shipit:

**Comment by Eilon** [comment]
Make sure you run this too and update the generated CPP files as part of this commit.

**Comment by davidfowl** [comment]
I just ran into this. :shipit:

**Comment by Eilon** [comment]
You ran into it? It's not merged yet is it?

**Comment by davidfowl** [comment]
I ran a build and it set the header back to the wrong one.

**Comment by Eilon** [comment]
Ohhh I see. So we already updated the headers, right. Well then merge @troydai 's PR then :smile: I forgot the headers already updated.

**Pull request merged**
