### PR TITLE
Rename Microsoft.Dnx.Runtime.Json.Sources -> Microsoft.Extensons.Json.Parser.Sources

### LINKED ISSUE #2871: Rename Microsoft.Framework.* to Microsoft.Extensions.*
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #2871

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Don't forget to update the watcher too https://github.com/aspnet/dnx-watch/blob/dev/src/Microsoft.Dnx.Watcher.Core/project.json#L8

**Comment by pranavkm** [comment]
Yup. I'll create a follow up once we have that package. It won't fail immediately with the rename since the old package will still exist.

**Comment by davidfowl** [comment]
And the test host

**Comment by pranavkm** [comment]
@davidfowl  the TestHost uses Newtonsoft.Json.

**Pull request closed without merging**
