### PR TITLE
"dnu publish" updates 'projects' property in global.json

### PR DESCRIPTION
**Pull request by ChengTian**
parent https://github.com/aspnet/dnx/issues/2169

@davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
No tests?

**Comment by ChengTian** [comment]
Added test for this

**Comment by ChengTian** [comment]
Rebased after runtime renaming.

This is quite straightforward change, please help to review @muratg @troydai @moozzyk @BrennanConroy

**Comment by muratg** [comment]
Looks good. :shipit:

**Pull request merged**
