### PR TITLE
Revert 71d9338.

### PR DESCRIPTION
**Pull request by cesarbs**
Re-enable tests that were causing build failures.

#3013

### CODE REVIEW

**Comment by cesarbs** [comment]
@victorhurdugaci @davidfowl @moozzyk @JunTaoLuo

**Comment by victorhurdugaci** [comment]
:shipit:

**Comment by moozzyk** [comment]
What has changed that you can now enable the tests without any other change?

**Comment by victorhurdugaci** [comment]
It was a bootstrapping issue

**Comment by moozzyk** [comment]
@victorhurdugaci - not sure what it means... was it environmental?

**Pull request closed without merging**
