### PR TITLE
Prevent a concurrent collection edit in breadcrumbs writing

### PR DESCRIPTION
**Pull request by victorhurdugaci**
Fixes https://github.com/aspnet/dnx/issues/2876

Please review @moozzyk @Tratcher

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by davidfowl** [comment]
How does this happen?

**Comment by moozzyk** [comment]
@davidfowl  `dnx --appbase . Microsoft.Dnx.ApplicationHost Microsoft.Dnx.ApplicationHost web` (transformed from `dnx -p Microsoft.Dnx.ApplicationHost web`) - both hosts were on the stack and since breadcrumb writing is not blocking and happens on a background thread both started writing to a file.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/commit/818575c20178103a5b61a30867e68f35995bacbb

**Comment by victorhurdugaci** [comment]
@davidfowl that can happen if write is called multiple times. And it happened because of what @moozzyk and @Tratcher said

**Comment by davidfowl** [comment]
Hah, I guess this is just being defensive then.

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
