### PR TITLE
porting OptionalFrameworks concept from NuGet

### LINKED ISSUE #2967: Unable to match dependency for PCL framework
Build error: The dependency Newtonsoft.Json 6.0.8 in project ClientRuntime does not support framework .NETPortable,Version=v4.5,Profile=Profile111 with the following configuration.

```
"frameworks": {
    ".NETPortable,Version=v4.5,Profile=Profile111": {
      "frameworkAssemblies": {
      },
      "dependencies": {
        "Newtonsoft.Json": "6.0.8"
      }
    },
```
Version: Beta-7

Looks like there is a problem matching path in a package "portable-net45+wp80+win8+wpa81" with the path generated by the portable profile.

### PR DESCRIPTION
**Pull request by anurse**
fixes #2967 

I tried to write some tests but they are tricky to get working because they depend on Xamarin being installed... I've hand-verified it though.

/review @davidfowl
/fyi @stankovski

### CODE REVIEW

**Comment by stankovski** [comment]
@anurse thanks!

**Comment by davidfowl** [comment]
Why does travis hate you?

**Comment by anurse** [comment]
"failed to locate libcoreclr with error libunwind-x86_64.so.8: cannot open shared object file: No such file or directory"

I don't really know...

**Comment by anurse** [comment]
@BrennanConroy says Travis broke something. Despite our build explicitly asking for Ubuntu 14.04, we're now getting 12.04 again. If you give me a squirrel I'll just merge and keep a close eye on the Linux build.

**Comment by davidfowl** [comment]
:shipit:

**Comment by stankovski** [comment]
@anurse what happened to this PR? Did the fix ever get into RC2 nightlies?

**Comment by davidfowl** [comment]
Yes it got merged

**Comment by stankovski** [comment]
I'm still seeing the issue in 1.0.0-rc2-16177

**Pull request closed without merging**
