### PR TITLE
Switch to Socket.Accept

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by davidfowl** [comment]
Did you test it? :smile: :shipit: once things pass that are supposed to pass

**Comment by troydai** [comment]
Ran functional test and run with VS on a sample project

**Comment by davidfowl** [comment]
Once you have it working. Make sure it doesn't break on mono

**Comment by davidfowl** [comment]
@troydai You gonna merge this?

**Comment by troydai** [comment]
I'll merge this today after some test on Mono.

**Pull request merged**
