### PR TITLE
Quoted dnu script paths to allow spaces

### PR DESCRIPTION
**Pull request by salerth**
Quoted dnu script paths to support spaces in the path

#1735

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@salerth__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by davidfowl** [comment]
Do dnx as well?

**Comment by salerth** [comment]
Just starting with .net on OSX, but after this fix I managed to run dnu restore and then dnx . kestrel just fine.

**Comment by ChengTian** [comment]
Merged: https://github.com/aspnet/dnx/commit/c076b0417dd998c2252d6ae88bc82a2dbf4777d8

**Pull request closed without merging**
