### PR TITLE
Fix #1739 by printing the LoaderExceptions property when a ReflectionTypeLoadException occurs

### LINKED ISSUE #1739: Print the LoaderExceptions property when a ReflectionTypeLoadException occurs
I ran into the following error today:

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.TryGetEntryPoint(Assembly assembly, IServiceProvider serviceProvider, Object& instance, MethodInfo& entryPoint)
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

It would be very helpful if the value of LoaderExceptions was printed automatically, cause right now there's no easy way to get it.

### PR DESCRIPTION
**Pull request by xPaw**
I'm not entirely sure this is an ideal fix, but it should do the job.

### CODE REVIEW

**Comment by davidfowl** [comment]
@xPaw Please read the coding guidelines. We don't accept patches to the master branch.

**Comment by xPaw** [comment]
@davidfowl I must be blind, but I can't see anything about branches in the contributing guide.

**Comment by davidfowl** [comment]
https://github.com/aspnet/Home/wiki/Engineering-guidelines#branch-strategy

**Comment by xPaw** [comment]
Recreated as #2345

**Pull request closed without merging**
