### PR TITLE
Replace NotNullAttribute with thrown exceptions

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by muratg** [comment]
Some code is moving around a little bit (cc @pakrym @anurse @davidfowl) but since this is automatically done and not too much overhead I say :shipit:

**Comment by pranavkm** [comment]
Neat. Just trying to get rid of it : https://github.com/aspnet/Common/pull/54

**Comment by muratg** [comment]
:+1:

**Comment by victorhurdugaci** [comment]
:shipit:

**Pull request closed without merging**
