### PR TITLE
Don't wait for debugger if no --debug switch...

### PR DESCRIPTION
**Pull request by moozzyk**
...even if DNX_DEBUG_PID_PATH defined

### CODE REVIEW

**Comment by troydai** [comment]
:shipit:

**Comment by anurse** [comment]
:shipit:

**Comment by moozzyk** [comment]
Plans have changed - we will not be using `DNX_DEBUG_PID_PATH` at all... so I removed even more code

**Comment by anurse** [comment]
:shipit:

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
