### PR TITLE
Update increamental build script

### PR DESCRIPTION
**Pull request by troydai**
This addresses the issue of incorrectly running batchcopy.sh on *nix.

/cc @dougbu @halter73

### CODE REVIEW

**Comment by dougbu** [comment]
:shipit: 

Good thing at least a few special characters are shared between `bash` and `cmd` :smiley_cat:

**Comment by troydai** [comment]
/cc @davidfowl 

Another reason that script execution shouldn't be DNX's business.

**Comment by davidfowl** [comment]
Not saying this is wrong but why are quotes needed?

**Comment by dougbu** [comment]
> why are quotes needed?

Were not needed before because we weren't executing scripts using a shell on Linux. Now that scripts work the same way (a vague approximation at least) on Windows and Linux, need to disable globbing of the input parameter and leave that to `batchcopy.sh`.

**Comment by dougbu** [comment]
For example Travis logs now show expected output during build stage:
```
Executing script 'postbuild' in project.json
Copy From: /home/travis/build/aspnet/dnx/src/Microsoft.Framework.Runtime.Loader/bin/Debug/dnx451/*.*
       To: /home/travis/build/aspnet/dnx/src/Microsoft.Framework.Runtime.Loader/../../artifacts/build/dnx-clr-win-x86/bin
Copy From: /home/travis/build/aspnet/dnx/src/Microsoft.Framework.Runtime.Loader/bin/Debug/dnx451/*.*
       To: /home/travis/build/aspnet/dnx/src/Microsoft.Framework.Runtime.Loader/../../artifacts/build/dnx-mono/bin
Copy From: /home/travis/build/aspnet/dnx/src/Microsoft.Framework.Runtime.Loader/bin/Debug/dnxcore50/*.*
       To: /home/travis/build/aspnet/dnx/src/Microsoft.Framework.Runtime.Loader/../../artifacts/build/dnx-coreclr-win-x86/bin
```

And AppVeyor log shows Windows script is a bit noisier than Linux but unchanged with this change:
```
Executing script 'postbuild' in project.json 
run: xcopy /F /Y /I C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnx451\*.* C:\projects\dnx\src\Microsoft.Framework.Runtime\..\..\artifacts\build\dnx-clr-win-x86\bin 
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnx451\Microsoft.Framework.Runtime.dll -> C:\projects\dnx\artifacts\build\dnx-clr-win-x86\bin\Microsoft.Framework.Runtime.dll
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnx451\Microsoft.Framework.Runtime.pdb -> C:\projects\dnx\artifacts\build\dnx-clr-win-x86\bin\Microsoft.Framework.Runtime.pdb
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnx451\Microsoft.Framework.Runtime.xml -> C:\projects\dnx\artifacts\build\dnx-clr-win-x86\bin\Microsoft.Framework.Runtime.xml
3 File(s) copied
run: xcopy /F /Y /I C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnx451\*.* C:\projects\dnx\src\Microsoft.Framework.Runtime\..\..\artifacts\build\dnx-mono\bin 
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnx451\Microsoft.Framework.Runtime.dll -> C:\projects\dnx\artifacts\build\dnx-mono\bin\Microsoft.Framework.Runtime.dll
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnx451\Microsoft.Framework.Runtime.pdb -> C:\projects\dnx\artifacts\build\dnx-mono\bin\Microsoft.Framework.Runtime.pdb
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnx451\Microsoft.Framework.Runtime.xml -> C:\projects\dnx\artifacts\build\dnx-mono\bin\Microsoft.Framework.Runtime.xml
3 File(s) copied
run: xcopy /F /Y /I C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnxcore50\*.* C:\projects\dnx\src\Microsoft.Framework.Runtime\..\..\artifacts\build\dnx-coreclr-win-x86\bin 
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnxcore50\Microsoft.Framework.Runtime.dll -> C:\projects\dnx\artifacts\build\dnx-coreclr-win-x86\bin\Microsoft.Framework.Runtime.dll
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnxcore50\Microsoft.Framework.Runtime.pdb -> C:\projects\dnx\artifacts\build\dnx-coreclr-win-x86\bin\Microsoft.Framework.Runtime.pdb
C:\projects\dnx\src\Microsoft.Framework.Runtime\bin\Debug\dnxcore50\Microsoft.Framework.Runtime.xml -> C:\projects\dnx\artifacts\build\dnx-coreclr-win-x86\bin\Microsoft.Framework.Runtime.xml
3 File(s) copied
```

**Comment by davidfowl** [comment]
:shipit: I wonder what other scripts we broke

**Comment by dougbu** [comment]
> I wonder what other scripts we broke

XRE is the only repo in aspnet that uses the scripts feature in `project.json` files. And @troydai's change updates all of those files. So nothing within our system.

However now that `bash` is consistently involved, some who worked around the old system may need to update their `project.json` files too.

**Comment by davidfowl** [comment]
> XRE is the only repo in aspnet that uses the scripts feature in project.json files. And @troydai's change updates all of those files. So nothing within our system.

However now that bash is consistently involved, some who worked around the old system may need to update their project.json files too.

Except you're forgetting all of the people who ever used that feature outside of the ASP.NET team.

**Comment by dougbu** [comment]
> Except you're forgetting all of the people who ever used that feature outside of the ASP.NET team.

That's who I meant when I said "some who worked around ...". The subset of those people who work only on Linux may have done something that needs a slightly different syntax in their `project.json` files now.

The good news however is that more `project.json` files can be written to work consistently on Windows and non-Windows machines. For example `>` in a `"scripts"` command now also works on Linux.

**Pull request merged**
