### PR TITLE
Special casing "runtimes" folder to prevent pruning it during publish

### PR DESCRIPTION
**Pull request by moozzyk**
This "fixes" #2858 

This should be fixed properly with #2628

### CODE REVIEW

**Comment by davidfowl** [comment]
Make this fix in release

**Comment by moozzyk** [comment]
Yeah. It's rebased on release. Forgot to change the branch when creating the PR.

**Comment by davidfowl** [comment]
:shipit:

**Comment by troydai** [comment]
Any tests?

**Comment by moozzyk** [comment]
@troydai - yes, ServerTests are all failing because of this.

**Pull request merged**
