### PR TITLE
Microsoft.Framework -> Microsoft.Dnx renames

### PR DESCRIPTION
**Pull request by victorhurdugaci**
Fixes https://github.com/aspnet/dnx/issues/1855 
Fixes https://github.com/aspnet/Testing/issues/90 
Fixes https://github.com/aspnet/Testing/issues/125

- Latest WTE works with the new renames (including test discovery)
- All tests pass (with the changes in testing and aspnet.xunit)
- Travis/Appveyor will not pass because of bootstrapping issues (will hack the CI when I merge)

- Renames:

image

Please review: @anurse @davidfowl @troydai @muratg

### CODE REVIEW

**Comment by davidfowl** [comment]
You missed `dnx.mono.managed`

**Comment by anurse** [comment]
Break early, fix early :P. I say :shipit: with the `dnx.mono.managed` rename. Can't do a ton of reviewing because of the scale of the change, but the longer we wait, the more backed up things get.

**Comment by davidfowl** [comment]
Don't do that. Fix the name. It's super easy.

**Comment by troydai** [comment]
Didn't and can't possibly go through the changes. Given that runtime tests and WTE pass let's get this in as early as possible so that potential issues will surface earlier.

:shipit:

**Comment by davidfowl** [comment]
Please rename the mono assembly in this change. It's localized to the dnx repository and will take 5 minutes.

**Comment by muratg** [comment]
Let's do the change: `dnx.mono.managed` -> `Microsoft.Dnx.DomainManager.Mono` and :shipit: and find issues as early as possible.

**Comment by anurse** [comment]
To be fair, I meant :shipit: AFTER fixing the Mono rename. Sorry if that wasn't clear.

**Comment by davidfowl** [comment]
Lets do that and then rename again. I don't know where DomainManager comes from but only CLR has a domain manager and I don't even remember that name in the original rename list.

**Comment by muratg** [comment]
It was discussed in the issue (https://github.com/aspnet/dnx/issues/1855) last week. Original list suggested merging those into `dnx.host`.  Someone (Pawel?) had a good reason why that's not a good idea.  I agree DomainManager is not exactly true in all of them.  

Any suggestions?  

Can you also fully review the table on the top to make sure you agree with all the names?

**Comment by anurse** [comment]
To be fair, the CoreCLR has a "DomainManager" but it's not an App Domain Manager :).

I still like merging `dnx.mono.managed`, `dnx.coreclr.managed` and `dnx.host` into one assembly and only keeping `dnx.clr.managed` separate. The reason the CLR one has to be separate is that it has to have a strong-name. We want to keep it separate so that it can have a strong-name without requiring that every other assembly have a strong-name (due to virality). So the CLR entry point is an exception to the merge, but only because of that specific reason.

My full proposal is as follows:

`dnx.coreclr.managed` + `dnx.host` (+ `dnx.mono.managed` if possible) -> `Microsoft.Dnx.Host`
`dnx.mono.managed` (if merging is not possible) -> `Microsoft.Dnx.Host.Mono`
`dnx.clr.managed` -> `Microsoft.Dnx.Host.DomainManager`

**Comment by victorhurdugaci** [comment]
PR updated:
dnx.mono.managed -> Microsoft.Dnx.DomainManager.Mono for consistency.

**Comment by victorhurdugaci** [comment]
Updated table:

image

**Comment by victorhurdugaci** [comment]
Now that I'm looking at the names maybe all Microsoft.Dnx.DomainManager.* should be Microsoft.Dnx.Host.* ...

**Comment by anurse** [comment]
Agreed, do that rename and get this in. We can debate merging the Hosts later, it won't affect anything else.

**Comment by victorhurdugaci** [comment]
Updated. Will have to rebase again because someone (looking at you @ChengTian ) merged a PR that conflicts with this one.

**Comment by victorhurdugaci** [comment]
Okay. Rebased and ready for merge. Will update the CI drops to have the new dnx and then I'll merge everything. Expect breaks

**Pull request merged**
