### PR TITLE
Avoid `async` and Unwrap overhead in Bootstrapper

### PR DESCRIPTION
**Pull request by Maxwe11**

### CODE REVIEW

**Comment by davidfowl** [comment]
The change looks fine but is there any real overhead?

**Comment by Maxwe11** [comment]
@davidfowl 
- `.Unwrap()` allocates TaskCompletionSource
- compilers generate a lot of code for `async` methods which is unnecessary in this case because we awaiting on completed task.

**Comment by davidfowl** [comment]
@Maxwe11 sure but have you measured anything?

**Comment by davidfowl** [comment]
Can you make the change here too https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.ApplicationHost/Program.cs#L89

**Comment by Maxwe11** [comment]
>sure but have you measured anything?

It's hard to measure it but in general we avoid TaskCompletionSource allocation :smile:  (which if I understand the code correctly will be in memory while user's Main executed)

>Can you make the change here too

done

**Comment by davidfowl** [comment]
@Maxwe11 in general, changes that claim to improve performance should have performance tests/metrics associated with change. 

Still I like this change because it simplifies the logic (assuming nothing regressed like exception behavior) but all of the tests passed :smile:

**Pull request merged**
