### PR TITLE
Split and expose more of entry point apis

### PR DESCRIPTION
**Pull request by pakrym**
https://github.com/aspnet/Testing/issues/180
/cc @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
For the test host? It's not worth it. Use the activator utilities in common.

**Comment by pakrym** [comment]
I don't wan't to duplicate entry point finder logic

**Comment by davidfowl** [comment]
It isn't the same though. You're building a different test entry point for the test infrastructure.

**Comment by pakrym** [comment]
Yes,  but I will search for the main (which should be there) and look for a second one in same class.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Oct 28, 2015 at 5:06 PM -0700, "David Fowler" <notifications@github.com<mailto:notifications@github.com>> wrote:


It isn't the same though. You're building a different test entry point for the test infrastructure.

-

**Pull request closed without merging**
