### PR TITLE
Rollback workaround for coreclr bug

### PR DESCRIPTION
**Pull request by pakrym**
It's working okay now.
Bug: https://github.com/dotnet/roslyn/issues/6326
Workaround commit: https://github.com/aspnet/dnx/commit/d1c5767c81e45bf564634391cefd5e0db4b849ff

@Eilon @JunTaoLuo

### CODE REVIEW

**Comment by Eilon** [comment]
Do we need this for RC1 or can it wait for RC2?

**Comment by pakrym** [comment]
You put it into rc1 but it definitely can got to rc2

**Comment by JunTaoLuo** [comment]
I agree, this is a minor change that can wait for rc2. Can you create another pull request for dev instead?

**Comment by Eilon** [comment]
Thanks, I moved the bug to RC2.

**Pull request closed without merging**
