### PR TITLE
Fix sporadic exception thrown during "kpm restore"

### PR DESCRIPTION
**Pull request by ChengTian**
The original approach is problematic: it creates the folder `<packages>/<PackageName>/<RandomName>` as temporary folder. However, some threads may treat `<RandomName>` as a version number and read nuspec from it. Directory.Move() will fail when a file in it is being read.

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:  Verify on mono

**Comment by ChengTian** [comment]
Verified on Mono and it works well

**Comment by davidfowl** [comment]
:shipit: !

**Comment by ChengTian** [comment]
Thanks for signing off. It's not an urgent change, so I guess it's better to check in next Monday after renaming.

**Pull request merged**
