### PR TITLE
Move abstractions around

### PR DESCRIPTION
**Pull request by pakrym**
Not ready atm, just preview.

1. Remove call context locator 
2. Remove IRuntimeServices
3. Remove IServiceProviderLocator
4. Moved Compilation stuff to compilation abstractions

Have an issue with RuntimeOptions, wana put it to Dnx.Runtime but DesignTimeHost depends on it,

@davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
:shipit:

**Comment by pakrym** [comment]
Removed IApplicationShutdown

**Comment by davidfowl** [comment]
@pakrym Where?

**Comment by pakrym** [comment]
@davidfowl In secret not commited changes

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
