### PR TITLE
Pawelka/coreclr rewrite

### PR DESCRIPTION
**Pull request by moozzyk**
@janvorli - can you take a look at this? This (at least "Rewriting CoreClr bootstrapper to use new runtime API" part) is related to the [change](https://github.com/dotnet/coreclr/commit/441a97709757ec1b6edcaadb733941e64af8fb60) you made

/cc @davidfowl @BrennanConroy

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Tested on Mac and this gets rid of the Trace/BPT error we were seeing.

**Comment by moozzyk** [comment]
Yay!

**Comment by davidfowl** [comment]
Feels like we should have a constant for this `"Microsoft.Dnx.Host.CoreClr"` as it's used in several places in the file. Or at least something like:

```
bootstrapperAssemblyName = "Microsoft.Dnx.Host.CoreClr";
bootstrapperAssemblyFileName = "Microsoft.Dnx.Host.CoreClr.dll";
bootstrapperAssemblyFullName = "Microsoft.Dnx.Host.CoreClr, 1.0.0.0, ...."
```

**Comment by janvorli** [comment]
LGTM
@moozzyk Please ignore the comment on the ExecuteAssembly, I have missed the fact that there were two commits.

**Comment by moozzyk** [comment]
@janvorli I think loading libcoreclrpal.so was added by @ellismg sometime in spring. It has not failed since so no one was aware it is not needed. I will remove loading this lib.

**Comment by moozzyk** [comment]
@davidfowl - created a #define for Microsoft.Dnx.Host.CoreClr but it does not look prettier...

**Pull request merged**
