### PR TITLE
fix the build by reporting all linuxes as ubuntu.14.04 for now...

### PR DESCRIPTION
**Pull request by anurse**
Also had to rebuild the test package.

It's not pretty... I'm filing an issue to fix this linux RID thing in RC 1 once and for all :)

/cc @BrennanConroy @muratg @davidfowl 

I'd like to see Travis pass before polluting release with changes that won't actually work.

### CODE REVIEW

**Comment by anurse** [comment]
Filed https://github.com/aspnet/dnx/issues/2881 to fix this in RC...

**Comment by BrennanConroy** [comment]
As long as the nupkg got built correctly :shipit:

**Comment by anurse** [comment]
I can send you a Hex diff if you want ;P

**Comment by moozzyk** [comment]
:ship: :it:

**Comment by anurse** [comment]
Merged to both `release` and `dev`

**Pull request merged**
