### PR TITLE
Fix for #887

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by davidfowl** [comment]
I think you should change the scripts after this change goes in. Otherwise we won't be able to do Dev until coherence passes

**Comment by BrennanConroy** [comment]
Can we add linux and darwin to the postbuild scripts?

**Comment by davidfowl** [comment]
@BrennanConroy Sure but not as part of this fix.

**Comment by BrennanConroy** [comment]
File #2684

**Comment by moozzyk** [comment]
@davidfowl this was one of the reasons why scripts are updated as a separate commit - so that they can be committed separately

**Comment by davidfowl** [comment]
@moozzyk The PR shows both. Hard to know what you'll commit

**Comment by moozzyk** [comment]
@davidfowl - I will commit scripts separately after coherence with the first two commits passes - and it can only happen if I get a ship it :)

**Comment by davidfowl** [comment]
:shipit:

**Comment by davidfowl** [comment]
This can be closed right? @moozzyk

**Comment by moozzyk** [comment]
Yes. I will close this. The scripts won't go in in the current state. They either need to be redone a little bit or not touched. At the moment - because we have a hardcoded Debug folder in the source path nothing is being copied on the CI which is a good thing.

**Comment by davidfowl** [comment]
@moozzyk Can you make sure we have a task tracking that. We should be using this change right now to make sure it works well.

**Comment by moozzyk** [comment]
OK. Will create one and assign to myself.

**Pull request closed without merging**
