### PR TITLE
Remove Configuration from IApplicationEnvironment

### PR DESCRIPTION
**Pull request by pakrym**
Also drop SetData/GetData
Issue: https://github.com/aspnet/dnx/issues/2788

@JunTaoLuo @davidfowl @pranavkm @anurse  @troydai

### CODE REVIEW

**Comment by davidfowl** [comment]
Have you spoken to @pranavkm about how Razor will resolve this?

**Comment by davidfowl** [comment]
:shipit: I love it!

**Comment by pranavkm** [comment]
Doesn't look like we use this property in Mvc. There're places where we implement IApplicationEnvironment where it shows up, but that's about it.

**Comment by davidfowl** [comment]
Except, you do https://github.com/aspnet/Mvc/blob/737a8f3b1dd4c8067fc671a08e3cac0d7d88cd48/src/Microsoft.AspNet.Mvc.Razor/Compilation/CompilationOptionsProviderExtension.cs#L43

**Comment by pakrym** [comment]
@davidfowl  `if (environment.IsDevelopment()) { ... } ` ?

**Comment by davidfowl** [comment]
@pakrym Commit this change. I think razor needs a specific option for this on the razor view engine options.

**Comment by pakrym** [comment]
https://github.com/aspnet/Mvc/pull/3632

**Pull request merged**
