### PR TITLE
teach dnx about netcore50 compat with netportable50

### PR DESCRIPTION
**Pull request by anurse**
We're still locking down the netportable name, but this logic is sound no matter the final name :).

/cc @bricelam @troydai @muratg @davidfowl

### CODE REVIEW

**Comment by bricelam** [comment]
:shipit:

**Comment by bricelam** [comment]
I was able to build this locally and get it working. Thanks, @anurse

**Comment by troydai** [comment]
:shipit:

**Comment by bricelam** [comment]
Merged as 9b57562fc7f685d0399b1602318d3e8cc5d65770

**Pull request closed without merging**
