### PR TITLE
rename XRE.sln

### PR DESCRIPTION
**Pull request by anurse**
As far as I can tell nothing depends on this name other than the "Recent Solutions" list on dev machines. And this now looks odd among the other renames :)

/cc @Eilon @muratg @davidfowl

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@anurse__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Andrew Stanton-Nurse). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by davidfowl** [comment]
:shipit:

**Comment by anurse** [comment]
Will do, but only after @NTaylorMullen re-opens the dev branch :P

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by davidfowl** [comment]
:shipit:

**Pull request closed without merging**
