### PR TITLE
Use nameof operator

### PR DESCRIPTION
**Pull request by henkmollema**
#1823

### CODE REVIEW

**Comment by henkmollema** [comment]
Will also add a commit with using nameof in `src`.

**Comment by henkmollema** [comment]
Just rebased. Could someone take a look at this? :smile:

/cc @davidfowl @ChengTian

**Comment by moozzyk** [comment]
:ship::it:

**Comment by ChengTian** [comment]
Thank you for the contribution, I'll do local verification build and merge it.

**Comment by ChengTian** [comment]
Merged: https://github.com/aspnet/dnx/commit/95b5c7ba0044065a159ffb6b865eb8955eb5879b

**Pull request closed without merging**
