### PR TITLE
No more IApplicationShutdown

### PR DESCRIPTION
**Pull request by davidfowl**

### CODE REVIEW

**Comment by smbecker** [comment]
Is there a replacement for RequestShutdown?

**Comment by davidfowl** [comment]
For console apps process exit. For web apps there's IApplicationLifetime

**Comment by troydai** [comment]
:shipit:

**Comment by troydai** [comment]
Why Travis failed?

**Comment by davidfowl** [comment]
Legit failure. I'll look into it. Something strange

**Comment by anurse** [comment]
Well **someone** said we shouldn't review code until Travis passes soooooo... :trollface:

**Comment by anurse** [comment]
Assuming Travis passes without significant changes, :shipit:

**Comment by victorhurdugaci** [comment]
:shipit: after you fix Travis

**Comment by anurse** [comment]
What's the status of this @davidfowl ?

**Comment by davidfowl** [comment]
Dead in a fire

**Pull request closed without merging**
