### PR TITLE
cleared local nuget sources

### PR DESCRIPTION
**Pull request by tugberkugurlu**
Clearing local NuGet sources as it sends unnecessary bunch of requests during restore when building project.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@tugberkugurlu__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by davidfowl** [comment]
We don't make inconsistent changes to our NuGet.config files. We use a template in aspnet/Universe and copy that to all of the repositories. That said, I don't know if this works for us. 
@pranavkm @Praburaj  Can you see if this breaks NuGet.redirect.config?

**Comment by dougbu** [comment]
whether or not this breaks NuGet.redirect.config, it will definitely break local caches e.g. `$env:userprofile\.nuget`

**Comment by davidfowl** [comment]
@dougbu good point. We shouldn't do this

**Comment by tugberkugurlu** [comment]
@dougbu, @davidfowl So, does this mean that **we** shouldn't do this as well? :smile: 

Also, it was able to get the packages from the cache when I cleared the local sources. Is that a different cache?

**Comment by davidfowl** [comment]
not a cache, a local packages folder that we use by convention.

**Comment by pranavkm** [comment]
Is the `.nuget` still used? We install to the `.k` directory when you do `build install` which was the primarily use case for it. It's probably useful for testing `KoreBuild` but not a great deal outside of it?

**Comment by davidfowl** [comment]
Ah you're right, we do kpm packages add now for build install.

**Comment by dougbu** [comment]
well, as @pranavkm said and I made more definite
> It's ~~probably~~ useful for testing KoreBuild

is that no longer a valid scenario?

**Pull request closed without merging**
