### PR TITLE
#1508: Introduce resourceBuiltIn and contentBuiltin

### PR DESCRIPTION
**Pull request by troydai**
#1508

### CODE REVIEW

**Comment by troydai** [comment]
@davidfowl

**Comment by troydai** [comment]
Need review
/cc @muratg @victorhurdugaci @BrennanConroy

**Comment by victorhurdugaci** [comment]
:shipit:

**Comment by troydai** [comment]
Anticipate one more sign off.

**Comment by BrennanConroy** [comment]
:sheep: :it:

**Comment by davidfowl** [comment]
Verify nothing in universe breaks.

**Comment by troydai** [comment]
You're a second late. I'm running Universe now.

**Pull request merged**
