### PR TITLE
Update the metaprogramming example

### PR DESCRIPTION
**Pull request by Tragetaschen**
I updated my own code and thought this might be a good way to find out if I did it right

### CODE REVIEW

**Comment by davidfowl** [comment]
@Tragetaschen do you want to update this again?

**Comment by Tragetaschen** [comment]
Sure

**Comment by jasonwilliams200OK** [comment]
:+1:

**Comment by jasonwilliams200OK** [comment]
@davidfowl, please consider merging this PR.

**Comment by davidfowl** [comment]
@Tragetaschen this PR's been open for a while and has gotten stale (thanks to us). I'm going to close this out. Can you add an example to the Entropy repository instead? That's where we put samples like this.

**Pull request closed without merging**
