### PR TITLE
 * Replace System.Resources.ReaderWriter

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Moved ReaderWRiter to the new packages. Also made the tabbing here match other project.json's Add ?w=1 to the url to hide whitespace-only changes.

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by davidfowl** [comment]
Is this breaking something?

**Comment by ryanbrandenburg** [comment]
This is a part of https://github.com/aspnet/Localization/issues/199 @Eilon updated me in person and said we'd need to fix DNX too because they want to remove the old package.

**Comment by davidfowl** [comment]
Ok

**Comment by Eilon** [comment]
@davidfowl per @KrzysztofCwalina the old combo ReaderWriter package is going away (next week) and has already been split into separate Reader and Writer packages.

**Pull request closed without merging**
